### PR TITLE
New pointers-to svg icon

### PR DESCRIPTION
**Pull request by StevenCostiou**
Following svg format comment from @Rinzwind https://github.com/pharo-project/pharo-icon-packs/pull/15 and ergonomic comments from @labordep https://github.com/pharo-project/pharo/issues/17104 I propose to add this specific icon for the `pointersTo` command button: 

Capture d’écran 2024-09-27 à 10 08 57

The *objects.svg* icon would become reserved for object-centric tools.

If accepted and when merged, I will do the modifications in the UI to correctly use the icons.

I do not provide examples of how it looks in different themes because I took the same red color as from the *objects.svg* icon so it should render similarly I guess.

### CODE REVIEW

**Comment by StevenCostiou** [comment]
note: the thin bar over the icon is due to when I did a screenshot, but if you look at the svg file it's not there and the white background is actually transparent.

**Comment by Rinzwind** [comment]
The icon needs to be added to the script in ‘README.md’ which also needs to be executed to generate the PNG files, you could adopt [commit c2eb7bcccf from my fork](https://github.com/Rinzwind/pharo-icon-packs/commit/c2eb7bcccf).

**Comment by StevenCostiou** [comment]
could you make a PR to my branch?
i will merge it and it will automatically update this PR.

**Comment by Rinzwind** [comment]
Sure, I opened [pull request #1 in your fork](https://github.com/StevenCostiou/pharo-icon-packs/pull/1) for it.

**Comment by StevenCostiou** [comment]
> Sure, I opened [pull request #1 in your fork](https://github.com/StevenCostiou/pharo-icon-packs/pull/1) for it.

Thanks very much :) :)
I merged.

**Comment by StevenCostiou** [comment]
this one should be ok now I guess?

**Comment by Rinzwind** [comment]
Seems OK to me.

@jecisc Could you maybe merge this?

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
