### PR TITLE
Solve issue 17697 by moving the icons from the image to this git

### PR DESCRIPTION
**Pull request by VincentBlondeau**

### CODE REVIEW

**Comment by estebanlm** [comment]
Hi, 
repo icons are cool, but: 
1. remotesManager\* icons are based on old eclipse theme and they should be based on idea11 icons. You can take the ones I downloaded  from here: https://dl.dropboxusercontent.com/u/7684634/idea-community-icons.zip to pick more appropriate ones (I know, they should be in a more visible place, but for now is where I could upload them)
2. Icon files now do not have the "Icon" suffix. See the others. 

I will accept PR with this corrections immediately :)

**Comment by estebanlm** [comment]
btw I know this is how it was before, but we can take the opportunity to fix it isn't? :)

**Comment by VincentBlondeau** [comment]
Ok. You can merge.
As soon you did it, I will commit some changes in Versionner and Catalog due to the renaming of the icons.

**Comment by estebanlm** [comment]
... but, if you are going to change versionner and catalog, this might be delayed until Pharo 5 launches

**Pull request merged**
